In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("../data/raw/market_data.csv", index_col="Date", parse_dates=True)

data.head()

,BND,GLD,IWM,QQQ,SPY,VNQ,VTI
Date,,,,,,,
2010-01-04,48.983265,109.800003,51.457939,40.341606,85.027954,23.803865,43.220066
2010-01-05,49.126484,109.699997,51.280987,40.341606,85.253014,23.777147,43.385986
2010-01-06,49.107826,111.510002,51.232735,40.098267,85.313026,23.734404,43.446304
2010-01-07,49.070477,110.820000,51.610748,40.124321,85.673203,23.990875,43.627300
2010-01-08,49.120262,111.370003,51.892258,40.454567,85.958298,23.814548,43.770596

In [3]:
returns = data.pct_change().dropna()

returns.head()

,BND,GLD,IWM,QQQ,SPY,VNQ,VTI
Date,,,,,,,
2010-01-05,0.002924,-0.000911,-0.003439,0.000000,0.002647,-0.001122,0.003839
2010-01-06,-0.000380,0.016500,-0.000941,-0.006032,0.000704,-0.001798,0.001390
2010-01-07,-0.000761,-0.006188,0.007378,0.000650,0.004222,0.010806,0.004166
2010-01-08,0.001015,0.004963,0.005454,0.008231,0.003328,-0.007350,0.003285
2010-01-11,0.000381,0.013289,-0.004030,-0.004082,0.001397,0.005834,0.001378

In [4]:
features = pd.DataFrame(index=returns.index)

features["SPY_return"] = returns["SPY"]

features["SPY_lag1"] = returns["SPY"].shift(1)
features["SPY_lag2"] = returns["SPY"].shift(2)
features["SPY_lag3"] = returns["SPY"].shift(3)

features.head()

            SPY_return  SPY_lag1  SPY_lag2  SPY_lag3
Date
2010-01-05    0.002647       NaN       NaN       NaN
2010-01-06    0.000704  0.002647       NaN       NaN
2010-01-07    0.004222  0.000704  0.002647       NaN
2010-01-08    0.003328  0.004222  0.000704  0.002647
2010-01-11    0.001397  0.003328  0.004222  0.000704

### Lag Variables
These Lag varaibles are made to show the effect of the past values of the variable of the current value of the variable. For example, GDP Lag 1 shows the effect of the GDP of the previous year on the current year's GDP.

I am looking at this because I want to see if there is any relationship between the past values of the variables and the current values of the variables. This can help me to understand if there is any lag effect in the data.

In [5]:
features["MA_10"] = data["SPY"].rolling(10).mean()
features["MA_50"] = data["SPY"].rolling(50).mean()

features.head()

            SPY_return  SPY_lag1  SPY_lag2  SPY_lag3  MA_10  MA_50
Date
2010-01-05    0.002647       NaN       NaN       NaN    NaN    NaN
2010-01-06    0.000704  0.002647       NaN       NaN    NaN    NaN
2010-01-07    0.004222  0.000704  0.002647       NaN    NaN    NaN
2010-01-08    0.003328  0.004222  0.000704  0.002647    NaN    NaN
2010-01-11    0.001397  0.003328  0.004222  0.000704    NaN    NaN

### Moving Averages
Moving averages smooth price fluctuations and help identify longer-term trends.

Shorter moving averages capture short-term momentum, while longer averages reflect broader market direction.

In [6]:
features["momentum_10"] = data["SPY"] / data["SPY"].shift(10) - 1
features["momentum_30"] = data["SPY"] / data["SPY"].shift(30) - 1

features.head()

,SPY_return,SPY_lag1,SPY_lag2,SPY_lag3,MA_10,MA_50,momentum_10,momentum_30
Date,,,,,,,,
2010-01-05,0.002647,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,0.000704,0.002647,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,0.004222,0.000704,0.002647,NaN,NaN,NaN,NaN,NaN
2010-01-08,0.003328,0.004222,0.000704,0.002647,NaN,NaN,NaN,NaN
2010-01-11,0.001397,0.003328,0.004222,0.000704,NaN,NaN,NaN,NaN

### Momentum Indicators

Momentum measures the strength of recent price movements.

Assets that have performed well recently often continue to outperform in the short term, a phenomenon known as momentum.

In [7]:
features["volatility_30"] = returns["SPY"].rolling(30).std()

features.head()

,SPY_return,SPY_lag1,SPY_lag2,SPY_lag3,MA_10,MA_50,momentum_10,momentum_30,volatility_30
Date,,,,,,,,,
2010-01-05,0.002647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,0.000704,0.002647,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,0.004222,0.000704,0.002647,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,0.003328,0.004222,0.000704,0.002647,NaN,NaN,NaN,NaN,NaN
2010-01-11,0.001397,0.003328,0.004222,0.000704,NaN,NaN,NaN,NaN,NaN

### Momentum Indicators

Momentum measures the strength of recent price movements.

Assets that have performed well recently often continue to outperform in the short term, a phenomenon known as momentum.

In [8]:
features["target"] = returns["SPY"].shift(-1)

features = features.dropna()

features.head()

,SPY_return,SPY_lag1,SPY_lag2,SPY_lag3,MA_10,MA_50,momentum_10,momentum_30,volatility_30,target
Date,,,,,,,,,,
2010-03-16,0.007966,0.000259,0.000087,0.004175,85.958284,83.721585,0.037523,0.067394,0.008871,0.005927
2010-03-17,0.005927,0.007966,0.000259,0.000087,86.318412,83.778155,0.042743,0.060880,0.008703,-0.000512
2010-03-18,-0.000512,0.005927,0.007966,0.000259,86.648532,83.829324,0.039063,0.065647,0.008617,-0.005062
2010-03-19,-0.005062,-0.000512,0.005927,0.007966,86.813410,83.870403,0.019235,0.094021,0.006139,0.005346
2010-03-22,0.005346,-0.005062,-0.000512,0.005927,87.023495,83.913621,0.024504,0.097601,0.006150,0.007033

### Target Variable

The target variable represents the next day's return for the SPY ETF.

Machine learning models will attempt to predict this value using the engineered features.

In [9]:
features.to_csv("../data/processed/features.csv")

### Why I Chose These Features

I chose these features because they are commonly used in financial modeling and have been shown to be effective in predicting stock returns. Lag variables can capture the influence of past values on current values, moving averages can identify trends, and momentum indicators can capture the strength of recent price movements. These features provide a comprehensive view of the market dynamics that may influence the target variable.